### ISSUE TITLE
ring

### ISSUE THREAD

**Issue by BmanDesignsCanada** [SaskArtists/SaskArtists#178]
Roger Ing's website has a lot of large files that no longer work. His site needs to be cleaned up and modernized with smaller file sizes.

**Comment by gemohandy** [comment]
Are the SWF objects the 'large flash files'? Because each of them is 5kb. The main reason his file is 1.5 megabytes is because there are _a lot_ of photos for the Utopia Photo Album, each around 30-40 kb or so. It may not seem like much, but there are 38 images there. They take up 1.3 megabytes all on their own. As much as I don't like the flash, I am not convinced that it is the problem.

**Comment by BmanDesignsCanada** [comment]
We should see what we can do about the album. His folder was ~200MB on the server. There is definitely something unnecessarily large in there.

**Comment by BmanDesignsCanada** [comment]
This has been solved.
