### ISSUE TITLE
Add text to afyfe

### ISSUE THREAD

**Issue by synixebrett** [SaskArtists/SaskArtists#309]

**Comment by synixebrett** [comment]
We will need to find out what text was supposed to be added, hopefully Wayne remembers what he wanted

**Comment by DarkerLonging** [comment]
He wants: (Summarizes the tribute to fyfe's grandfathers generation of artists. Is she cleaning them up? Or wiping them down the drain?) behind "Tribute to Regina 5". (psychedelic ambiguity of nature and self.) after "Nature Resting". (White on white.) behind "Ronald Bloor Sink". (Mandella) behind "Art McKay Sink". (Tartan) behind "Ted Godwin Sink". (Dreamscape) behind "Ken Lockhead Sink". (Colour Purity) behind "Doug Morton Sink". Remove "To get in contact" line. Get a quote from "Amber Fyfe leader post".  On the amber fyfe gallery add a quote instead of phone number.

**Comment by gemohandy** [comment]
Fixed by pull request #386
