### ISSUE TITLE
Alex Crease's page when entered comes up with error

### ISSUE THREAD

**Issue by eli9701** [SaskArtists/SaskArtists#450]
**when you click on Alex Crease's name to go to his page it instead directs you to an internal server error**

1. Go to Sask Artists 
2. Click on Alex Crease's page
3. See error

Expected behavior
I expected it to take me to Alex Crease's page and not to an Internal server issue

**Comment by gemohandy** [comment]
I heavily suspect this is an issue due to acrease's index being index.php, rather than index.html. Looking online, part of the issue may (_may_) be that we use include on the html files, rather than readfile. Apparently, this can potentially cause issues because the html is interpreted as php. I'm not sure if this is what's causing the issue, but it should probably be fixed at the same time.

**Comment by gemohandy** [comment]
Apparently, this was caused by weird write-access issues on the server side. Fortunately for us, this means there's nothing to change on the Github, because the issue doesn't actually exist on the Github. The issue has been dealt with on the server.
